version: '3.9'

services:
  db:
    container_name: db
    environment:
      PG_DATA: /var/lib/postgresql/data
    env_file:
      - ./.development.env
    image: postgres
    ports:
      - 54323:5432
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
